@extends('master')
@section('sliderBanner')
    @include('frontend.header.slider')
@stop
@section('container')
    @include('frontend.trangchu.whychoosesmartlinks.whychoosesmartlinks')
    @include('frontend.trangchu.analysiswebsite.analysiswebsite')
    @include('frontend.trangchu.services.services')
    @include('frontend.trangchu.consultants.consultants')
    @include('frontend.trangchu.prices.prices')
    @include('frontend.trangchu.lienhebaogia.lienhebaogia')
    @include('frontend.trangchu.tintuc.tintuc')
@stop